INSERT INTO Defines(Name, Value) VALUES('OPINION_WEIGHT_MARRIAGE', -35);
INSERT INTO Defines(Name, Value) VALUES('APPROACH_DECEPTIVE_MARRIAGE_WITH_PLAYER', 15);
INSERT INTO Defines(Name, Value) VALUES('APPROACH_FRIENDLY_MARRIAGE_WITH_PLAYER', 30);
INSERT INTO Defines(Name, Value) VALUES('APPROACH_HOSTILE_MARRIAGE_WITH_PLAYER', -50);
INSERT INTO Defines(Name, Value) VALUES('APPROACH_GUARDED_MARRIAGE_WITH_PLAYER', -50);
INSERT INTO Defines(Name, Value) VALUES('DOF_WEIGHT_CHANGE_FROM_MARRIAGE', 1);
INSERT INTO Defines(Name, Value) VALUES('DOF_WEIGHT_MODIFIER_FROM_MARRIAGE', 100);